import { Funnel_Display } from "next/font/google";
import "./globals.css";

import Navbar from "./components/navbar";
import LenisProvider from "./components/LenisProvider";

const funnelDisplay = Funnel_Display({
  variable: "--font-funnel-display",
  subsets: ["latin"],
});

export const metadata = {
  title: "Explore Cyber Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${funnelDisplay.variable} antialiased`}>
        <LenisProvider>
          <Navbar />
          {children}
        </LenisProvider>
      </body>
    </html>
  );
}
